version: '0.1'

services:
  db:
    image: postgres:15-alpine
    container_name: BancoDeDado
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: b2c6bd1f6305
    container_name: sistemaemprasarial
    restart: always
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME= ${POSTGRES_DB}
    depends_on:
      - db

  front:
    image: sha256:edfc78ea37d55cf4df3f42d9a753af95371dacdc02224d461f92442f74c04963
    container_name: app-react
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend


volumes:
  postgres_data: